import { Metadata } from "next";
import Hero from "@/src/components/landing/Hero";
import Nav from "@/src/components/landing/Nav";

export const metadata: Metadata = {
  title: "Nest",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="w-full h-full flex flex-col items-center justify-start relative">
      <Nav />
      <Hero />
    </div>
  );
}
